version: "3.9"
services:
  h3-project-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "h3_project_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

