spring:
  application:
    name: h3-project

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: h3-project-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "kz.h3project.events"
        spring.json.value.default.type: "kz.h3project.events.AppointmentCreatedEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/h3_project_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 'classpath:db.migration'

logging:
  level:
    org.flywaydb: DEBUG

server:
  port: 8080